"""empty message

Revision ID: 1c3e46b756c8
Revises: cc94085a3ff2
Create Date: 2019-05-06 21:28:54.030358

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1c3e46b756c8'
down_revision = 'cc94085a3ff2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('publisher_id', sa.Integer(), nullable=True))
    op.drop_constraint('book_ibfk_1', 'book', type_='foreignkey')
    op.create_foreign_key(None, 'book', 'publisher', ['publisher_id'], ['id'])
    op.drop_column('book', 'depart_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('depart_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'book', type_='foreignkey')
    op.create_foreign_key('book_ibfk_1', 'book', 'publisher', ['depart_id'], ['id'])
    op.drop_column('book', 'publisher_id')
    # ### end Alembic commands ###
